-- Script de Inicialização de Banco de Dados para Supabase
-- Cole isso no SQL Editor do Supabase e clique em "Run"

-- 1. Criação da tabela de Perfis (Profiles)
CREATE TABLE profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    github_username VARCHAR(255),
    bio VARCHAR(255),
    avatar_url VARCHAR(255),
    linkedin_url VARCHAR(255)
);

-- 2. Criação da tabela de Tecnologias (Technologies)
CREATE TABLE technologies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    icon_url VARCHAR(255)
);

-- 3. Criação da tabela de Projetos (Projects)
CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    repository_url VARCHAR(255),
    average_rating DOUBLE PRECISION DEFAULT 0.0,
    upvotes INTEGER DEFAULT 0,
    profile_id BIGINT NOT NULL,
    CONSTRAINT fk_projects_profile FOREIGN KEY (profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);

-- 4. Criação da tabela de Feedbacks
CREATE TABLE feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author VARCHAR(255),
    comment VARCHAR(255),
    rating INTEGER NOT NULL,
    project_id BIGINT NOT NULL,
    CONSTRAINT fk_feedbacks_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

-- 5. Criação da Tabela Intermediária (Project_Technology - Relacionamento N:N)
CREATE TABLE project_technology (
    project_id BIGINT NOT NULL,
    technology_id BIGINT NOT NULL,
    PRIMARY KEY (project_id, technology_id),
    CONSTRAINT fk_pt_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_pt_technology FOREIGN KEY (technology_id) REFERENCES technologies (id) ON DELETE CASCADE
);

-- 6. (Opcional) Inserindo alguns dados iniciais para você não começar com o banco vazio
INSERT INTO technologies (name, icon_url) VALUES 
('Java', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg'),
('Spring Boot', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg'),
('PostgreSQL', 'https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg');
